master Import/Export:411 ensure to export current branch, php version, repository name and url
conceptsandtraining/doil pull request #412
Opened 2024-02-14 09:14 UTC by daniwe4

2024-02-14 12:38 UTC, tbongers-cat requested changes

2024-02-14 12:38 UTC, tbongers-cat commented on app/src/Commands/Pack/ExportCommand.php
> +        $php_version = trim($this->docker->executeDockerCommandWithReturn("cate79_local", $cmd));
Hier soll wahrscheinlich nicht fix 'cate79_global' drin stehen =)

2024-02-14 12:38 UTC, tbongers-cat commented on app/src/Commands/Pack/ImportCommand.php
> +                $repo_added = true;
Bitte der Vollständigkeit halber $repo_added vorher mit false initialisieren.

2024-02-15 05:55 UTC, daniwe4 commented on app/src/Commands/Pack/ExportCommand.php
> +        $php_version = trim($this->docker->executeDockerCommandWithReturn("cate79_local", $cmd));
Done!

2024-02-15 05:56 UTC, daniwe4 commented on app/src/Commands/Pack/ImportCommand.php
> +                $repo_added = true;
Done!

2024-02-15 08:32 UTC, tbongers-cat approved these changes

2024-02-15 08:33 UTC, merged