master update/install: check for requirements docker compose and docker buildx
conceptsandtraining/doil pull request #421
Opened 2024-04-08 06:13 UTC by daniwe4

2024-04-09 14:12 UTC, tbongers-cat requested changes

2024-04-10 05:38 UTC, daniwe4 commented on setup/checks.sh
>  # return 255 if root has no docker-compose
Done!

2024-04-10 05:38 UTC, daniwe4 commented on setup/checks.sh
> +# return 255 if root has no docker-compose
Done!

2024-04-10 07:23 UTC, tbongers-cat approved these changes

2024-04-10 07:23 UTC, merged