master keycloak:449 add keycloak as IdP for doil managed ILIAS Instances
conceptsandtraining/doil pull request #474
Opened 2024-11-13 10:47 UTC by daniwe4

* add keycloak commands (down/login/restart/up)
* add saml states (enable-saml/disable-saml)
* add keycloak state
* add keycloak template
* update CHANGELOG
* update README
* add an update script
* tested so far on my local host

2024-11-13 15:08 UTC, tbongers-cat requested changes

2024-11-13 15:08 UTC, tbongers-cat commented on setup/stack/states/enable-saml/saml/init.sls
> +{% set samlpass = salt['grains.get']('samlpass', 'abcdef123456!!$') %}
Können wir die Standard-PW im Klartext irgendwie vermeiden?

2024-11-13 15:08 UTC, tbongers-cat commented on setup/stack/states/keycloak/keycloak/delete_keycloak_client.sh.j2
> +/opt/keycloak-25.0.5/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password {{ new_admin_password }}
Ist es eventuell sinnvoll, hier und an anderen Stellen die Version von Keycloak (25.0.5) variabel zu machen für spätere Updates?

2024-11-13 15:08 UTC, tbongers-cat commented on setup/stack/states/keycloak/keycloak/init.sls
> +# Please let that in as an example for default user creation
"Please leave this in..."

2024-11-13 15:08 UTC, tbongers-cat commented on setup/system.sh
> +  # Please let that in as an example for default user creation
Siehe oben

2024-11-13 15:08 UTC, tbongers-cat commented on setup/system.sh
> +  # Please let that in as an example for default user creation
Siehe oben

2024-11-13 15:08 UTC, tbongers-cat commented on setup/templates/proxy/conf/salt-startup.sh
Warum ist das ein "empty file"?

2024-11-13 15:08 UTC, tbongers-cat commented on setup/updates/update-20240917.sh
Waren die beiden Updatescripts nicht schon vorher da? Wo kommen die jetzt her?

2024-11-14 07:27 UTC, daniwe4 commented on setup/templates/keycloak/Dockerfile
> +RUN curl -fsSL -o jdk-21_linux-x64_bin.deb https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
Guter Hinweis.
Das hab ich auf der Oracle Website gefunden.

Oracle JDK 21 and later is available under the [Oracle No-Fee Terms and Conditions License](https://www.oracle.com/de/downloads/licenses/no-fee-license.html) which permits free use for all users.

2024-11-14 07:34 UTC, daniwe4 commented on setup/stack/states/keycloak/keycloak/init.sls
> +# Please let that in as an example for default user creation
done!

2024-11-14 07:34 UTC, daniwe4 commented on setup/system.sh
> +  # Please let that in as an example for default user creation
done!

2024-11-14 07:34 UTC, daniwe4 commented on setup/system.sh
> +  # Please let that in as an example for default user creation
done!

2024-11-14 07:42 UTC, daniwe4 commented on setup/updates/update-20240917.sh
done!
Eins war falsch benannt und eins ist beim Testen hinzugekommen.

2024-11-14 07:43 UTC, daniwe4 commented on setup/templates/proxy/conf/salt-startup.sh
Hier hat sich nur der File Mode geändert! 
644 -> 755

2024-11-14 07:45 UTC, daniwe4 commented on setup/stack/states/disable-saml/description.txt
> +description = ATTENTION: This will delete existing SAML configurations. Disables saml login in ILIAS and remove the instance from keycloak.
done!

2024-11-14 08:01 UTC, daniwe4 commented on setup/stack/config/master.cnf
> +  prevent-super-global-replacement:
done!

2024-11-14 08:33 UTC, daniwe4 commented on setup/stack/states/enable-saml/description.txt
> +description = ATTENTION: This will overwrite potentially existing SAML configurations. Enables saml login in ILIAS and add the instance to keycloak.
done!

2024-11-14 08:37 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/config.php.j2
> +$metadataSources = array();
done!

2024-11-14 09:09 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/init.sls
> +{% set samlpass = salt['grains.get']('samlpass', 'abcdef123456!!$') %}
Diese Passwort ist nur ein default Passwort falls samlpass nicht gefunden wird. Ausserdem wird der Zugriff per saml config eh verboten. Somit wäre es auch nur ein internes Passwort.

2024-11-14 13:34 UTC, daniwe4 commented on setup/stack/states/keycloak/keycloak/delete_keycloak_client.sh.j2
> +/opt/keycloak-25.0.5/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password {{ new_admin_password }}
done!
umgestellt auf /opt/keycloak/bin ...

2024-11-14 13:38 UTC, daniwe4 commented on setup/conf/doil.conf
> +keycloak_new_admin_password=12345
Das müsste dann in die Script update und install.
Das Update Script macht eine Abfrage mit dem Verweis auf die Datei.
Ich glaube das sollte reichen.

2024-11-14 13:55 UTC, daniwe4 commented on README.md
> +The corresponding users must be created in Keycloak and ILIAS.
done!

2024-11-14 15:19 UTC, tbongers-cat approved these changes

2024-11-20 18:08 UTC, klees requested changes
Hallo @daniwe4,

folgende Dinge sind mir generell aufgefallen:

* Im Keycloak-Container scheinen viele Dinge als root laufen zu sollen. Wollen wir das wirklich?
* Wir können für SimpleSAML in ILIAS einfach die ILIAS-DB mit nutzen. Beschreibung ist [hier](https://hub.cat-office.de/xwiki/bin/view/03%20Teams/cate-Infrastruktur%202/Knowledgebase/ILIAS/SAML-SSO%20im%20ILIAS-Standard%20einrichten/). Das erspart und sqlite (ein moving part weniger...) und außerdem kann dann auch ohne viel Hussle mit dem Adminer in die Tabellen von SimpleSAML geschaut werden.

Ansonsten: OASEM!!

Beste Grüße!

2024-11-20 18:08 UTC, klees commented on README.md
> +In order to use Saml for an Ilias instance, it must be ensured that a user is created in the
```suggestion
In order to use SAML for an Ilias instance, it must be ensured that a user is created in the
```

2024-11-20 18:08 UTC, klees commented on README.md
> +#### Cretae a user in ILIAS
Bekommen wir das nicht noch so hin, dass der Nutzer beim ersten Login per SAML auch erzeugt wird? Das wäre große Klasse =)

2024-11-21 05:59 UTC, daniwe4 commented on setup/templates/proxy/conf/salt-startup.sh
Die Datei konnte bisher nicht von supervisor aufgerufen werden. Das fällt nur auf wenn salt einmal den salt-key für den Proxy verwirft. Deswegen ist das bisher gut gegenagen.

2024-11-21 06:03 UTC, daniwe4 commented on setup/templates/mail/Dockerfile
> +RUN mkdir /root/.keycloak
Gut gesehen!
Da bin ich wohl in der falschen Datei gelandet.
Done!

2024-11-21 06:07 UTC, daniwe4 commented on setup/templates/keycloak/docker-compose.yml
> +    image: doil_keycloak:stable
Das 'doil_keycloak:stable' image erstelle ich mit dem Dockerfile selber.
Im Dockerfile zeiehe ich mir eine gepinnte Version ohne Updates.
`RUN curl -fsSL -o keycloak-25.0.5.zip https://github.com/keycloak/keycloak/releases/download/25.0.5/keycloak-25.0.5.zip`

2024-11-21 06:09 UTC, daniwe4 commented on setup/templates/keycloak/conf/startup.conf
> +autorestart=false
Ja, das 'sal-startup.sh' Script soll nur einmal beim Containerstart laufen.

2024-11-21 06:11 UTC, daniwe4 commented on setup/templates/keycloak/conf/startup.conf
> +user=root
Auch das ist meiner Meinung nach richtig, da das Script 'salt-startup' root cmd's ausführt.

2024-11-21 06:29 UTC, daniwe4 commented on setup/templates/keycloak/conf/salt-minion.conf
> +autorestart=false
autorestart ist nun true
Done!

2024-11-21 06:30 UTC, daniwe4 commented on setup/templates/keycloak/conf/mysql.conf
> +user=root
auch hier werden im scriipt Kommandos aufgerufen, die root Rechte brauchen.
`chown -R mysql:mysql /run/mysqld
chown -R mysql:mysql /var/lib/mysql`

2024-11-21 06:32 UTC, daniwe4 commented on setup/updates/update-20241113.sh
> +  doil_status_send_message "Install php sqlite extension on existing instances."
Ich hab einen Error in der ILIAS-Oberfläche angezeigt bekommen, dass die php Erweiterung sqlite fehlt.
Immer wenn ich unter Benutzerverwaltung die SAML Einstellungen aufgerufen habe.

2024-11-21 07:37 UTC, daniwe4 commented on setup/templates/keycloak/conf/keycloak-startup.conf
> +user=root
keycloak läuft nun unter dem nicht privilligierten user keycloak
Done!

2024-11-21 08:50 UTC, klees commented on setup/updates/update-20241113.sh
> +  doil_status_send_message "Install php sqlite extension on existing instances."
Kannst du das bitte nochmal prüfen? Ich glaube, dass hängt an der Config vom SimpleSAML, wenn die kein sqlite verwendet gibt es den Error auch nicht SWIW. Wenn es den trotzdem gibt ist was fishy, aber wohl nicht bei uns...

2024-11-21 14:07 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/addInstanceToKeycloak.sh.j2
> +KC_HOST={{ server_host_name }}
addInstanceToKeycloak.sh ist nun in php geschrieben
fehlt noch deleteInstanceFromKeycloak.sh

2024-11-22 06:38 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/addInstanceToKeycloak.sh.j2
> +KC_HOST={{ server_host_name }}
nun ist auch deleteInstanceFromKeycloak in PHP implementiert
Done!

2024-11-22 06:54 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/SetIdpV10.php.j2
Ich hab im cmd.run Teil das && durch ein ; ersetzt, so dass der rm Befehl auf jeden Fall ausgeführt wird.
Done!

2024-11-22 06:55 UTC, daniwe4 commented on README.md
> +In order to use Saml for an Ilias instance, it must be ensured that a user is created in the
Done!

2024-11-22 06:57 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/init.sls
> +      ilias_http_path: {{ doil_domain }}
Ja, ist er.

2024-11-22 07:08 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/config.php.j2
> +    'store.sql.dsn' => 'mysql:host=127.0.0.1;dbname=ilias',
sqlite wieder entfernt
Done!

2024-11-22 07:09 UTC, daniwe4 commented on setup/updates/update-20241113.sh
> +  doil_status_send_message "Install php sqlite extension on existing instances."
sqlite wieder entfernt
Done!

2024-11-22 07:11 UTC, daniwe4 commented on setup/templates/keycloak/Dockerfile
> +RUN curl -fsSL -o jdk-21_linux-x64_bin.deb https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
doil nutzt nun OpenJDK
Done!

2024-11-22 08:44 UTC, daniwe4 commented on setup/stack/states/enable-saml/saml/config.php.j2
> +    'baseurlpath' => '{{ ilias_http_path }}/',
beim Import wird die url angepasst wenn keycloak aktiv ist.

In die states en/disable -https wurde ein step rewrite_saml_config hinzugefügt. Dieser prüft ob es die saml Datei config.php gibt und ändert dann jeweils http/https.
Done!

2024-11-25 06:37 UTC, daniwe4 commented on README.md
> +#### Cretae a user in ILIAS
Done!

2024-11-25 07:14 UTC, klees approved these changes

2024-12-03 09:56 UTC, merged